version: '2'
services:
  web:
    build: .
    restart: always
    ports:
      - 8080:8080
    links:
      - mongo
    environment:
      - NODE_ENV=production
    command: ["./wait-for", "mongo:27017", "--", "npm", "start"]

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017